# Generated by Django 3.2 on 2021-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=15)),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.CharField(max_length=20)),
            ],
        ),
    ]
